[package]
name = "iced-demo"
version = "0.1.0"
authors = ["TENX-S <coldswind@pm.me>"]
edition = "2018"



[dependencies]
grp = { git = "https://github.com/TENX-S/grp.git", branch = "master" }
iced = { git =  "https://github.com/TENX-S/iced.git", branch = "master" }